import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContractWrite, usePrepareContractWrite } from "wagmi";
import styles from "../styles/Home.module.css";
import verbsDAOGovernance from "../data/VerbsDAOGovernance.json";
import { Button, HStack, Spacer, Text, VStack } from "@chakra-ui/react";

const Home: NextPage = () => {
  const { config } = usePrepareContractWrite({
    addressOrName: "0x48ADbf604c7ff9E2b2e8c01b243Ba446538972EA",
    contractInterface: verbsDAOGovernance.abi,
    functionName: "voteProposal",
  });

  const { data: txn, isLoading, isSuccess, write } = useContractWrite(config);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text className={styles.title}>Web3 Infinity DAO</Text>
        <VStack>
          <Text>
            Web3 Infinity DAO. As a member, you can vote on proposals or
            delegate votes to a third party. You can also create your own
            proposals.
          </Text>
          <HStack className={styles.proposalHeaderContainer}>
            <Text className={styles.proposalHeader}>Proposals</Text>
            <Button
              disabled={!write}
              onClick={() => write?.()}
              className={styles.submitButton}
            >
              Submit Proposal
            </Button>
          </HStack>
          <VStack className={styles.proposalStack}>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #131 Create educational resources regarding IPFS and Filecoin
                for local community.
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #130 Create a documentary on Filecoin and FIL-Singapore
                foundings.
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #129 Shoot a rocket into the moon with Web3 Infinity logo on the
                rocket tip.
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #128 Name a new frog species after Web3 Infinity.
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                {`#127 Change the name from "Web3 Infinity" to "Web3 to Infinity and
                Beyond".`}
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #126 Fund Nintendo and Animoca to create an NFT-based Web3
                Infinity game powered by IPFS.
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #125 Airdrops for everyone who owns at least 1 FIL!
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #124 Airdrops for everyone who owns at least 1 DOGE!
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
            <HStack className={styles.proposalContainer}>
              <Text className={styles.proposalTitle}>
                #123 Airdrops for everyone who owns at least 1 BTC!
              </Text>
              <Button
                disabled={!write}
                onClick={() => write?.()}
                className={styles.voteButton}
              >
                Vote on Proposal
              </Button>
            </HStack>
          </VStack>
        </VStack>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
